### ISSUE TITLE
Updated from 0.3.0 to 0.4.0 --> panic: runtime error

### ISSUE THREAD

**Issue by The34Goon** [edouardparis/lntop#104]
lntop version v0.4.0

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ac520]

goroutine 15 [running]:
github.com/edouardparis/lntop/ui/models.New(0x400044a9c0)
	/home/edouard/code/edouardparis/lntop/ui/models/models.go:28 +0x40
github.com/edouardparis/lntop/ui.newController(0x400044a9c0)
	/home/edouard/code/edouardparis/lntop/ui/controller.go:353 +0x24
github.com/edouardparis/lntop/ui.Run({0xdca940?, 0x400012e000}, 0x0?, 0x4000114a20)
	/home/edouard/code/edouardparis/lntop/ui/ui.go:21 +0x80
github.com/edouardparis/lntop/cli.run.func1()
	/home/edouard/code/edouardparis/lntop/cli/cli.go:66 +0x3c
created by github.com/edouardparis/lntop/cli.run
	/home/edouard/code/edouardparis/lntop/cli/cli.go:65 +0x114

**Comment by edouardparis** [comment]
Sorry for the disagreement, looks like setting the forward history panel options is not optional;
Please add to your config :
```toml
[views.fwdinghist]
columns = [
         "ALIAS_IN",	# peer alias name of the incoming peer
         "ALIAS_OUT",   # peer alias name of the outgoing peer
         "AMT_IN",	# amount of sats received
         "AMT_OUT",     # amount of sats forwarded
         "FEE",      	# earned fee
         "TIMESTAMP_NS",# forwarding event timestamp
#        "CHAN_ID_IN",  # channel id of the incomming channel
#        "CHAN_ID_OUT", # channel id of the outgoing channel
]

[views.fwdinghist.options]
START_TIME = { start_time = "-6h" }
MAX_NUM_EVENTS = { max_num_events = "333" }
```
